# DATE: 21-Oct-2025
# SEE: https://learn.microsoft.com/en-us/azure/developer/github/github-actions-key-vault
############################################################################################

  name: azure-keyvault
  on:
    push:
      branches: none # [ main ]
    pull_request:
      branches: none # [ main ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

  permissions:
        id-token: write
        contents: read
  jobs: 
    login-and-retrieve-secret:
      runs-on: ubuntu-latest
      environment: Production # Can show as not valid in VS Code, but ok if env is created in Github
      steps:
        - name: 'Az CLI login'
          uses: azure/login@v2.3.0
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
        - name: Retrieve secret from Key Vault
          id: keyvault
          uses: azure/CLI@v2.2.0
          with: # echo "::add-mask::$SECRET_VALUE"
            inlineScript: |
              SECRET_VALUE=$(az keyvault secret show --name Secret1 --vault-name ${{ secrets.KEYVAULT_NAME }} --query value -o tsv)
        
              echo "SECRET_VALUE=$SECRET_VALUE" >> $GITHUB_ENV
        
        - name: Use retrieved secret
          run: echo "The secret is successfully retrieved!"

        - uses: actions/checkout@v5 # Checkout the file deploy.sh
        - name: Use SECRET_VALUE in deployment
          run: |
            bash ./deploy.sh
          env:
            SECRET_VALUE: ${{ env.SECRET_VALUE }}